export enum Pair {
  ETHBTC = 'ETHBTC',
  LTCBTC = 'LTCBTC',
  BNBBTC = 'BNBBTC',
  NEOBTC = 'NEOBTC',
  QTUMETH = 'QTUMETH',
  EOSETH = 'EOSETH',
  SNTETH = 'SNTETH',
  BNTETH = 'BNTETH',
  BCCBTC = 'BCCBTC',
  GASBTC = 'GASBTC',
  BNBETH = 'BNBETH',
  BTCUSDT = 'BTCUSDT',
  ETHUSDT = 'ETHUSDT',
  HSRBTC = 'HSRBTC',
  OAXETH = 'OAXETH',
  DNTETH = 'DNTETH',
  MCOETH = 'MCOETH',
  ICNETH = 'ICNETH',
  MCOBTC = 'MCOBTC',
  WTCBTC = 'WTCBTC',
  WTCETH = 'WTCETH',
  LRCBTC = 'LRCBTC',
  LRCETH = 'LRCETH',
  QTUMBTC = 'QTUMBTC',
  YOYOBTC = 'YOYOBTC',
  OMGBTC = 'OMGBTC',
  OMGETH = 'OMGETH',
  ZRXBTC = 'ZRXBTC',
  ZRXETH = 'ZRXETH',
  STRATBTC = 'STRATBTC',
  STRATETH = 'STRATETH',
  SNGLSBTC = 'SNGLSBTC',
  SNGLSETH = 'SNGLSETH',
  BQXBTC = 'BQXBTC',
  BQXETH = 'BQXETH',
  KNCBTC = 'KNCBTC',
  KNCETH = 'KNCETH',
  FUNBTC = 'FUNBTC',
  FUNETH = 'FUNETH',
  SNMBTC = 'SNMBTC',
  SNMETH = 'SNMETH',
  NEOETH = 'NEOETH',
  IOTABTC = 'IOTABTC',
  IOTAETH = 'IOTAETH',
  LINKBTC = 'LINKBTC',
  LINKETH = 'LINKETH',
  XVGBTC = 'XVGBTC',
  XVGETH = 'XVGETH',
  SALTBTC = 'SALTBTC',
  SALTETH = 'SALTETH',
  MDABTC = 'MDABTC',
  MDAETH = 'MDAETH',
  MTLBTC = 'MTLBTC',
  MTLETH = 'MTLETH',
  SUBBTC = 'SUBBTC',
  SUBETH = 'SUBETH',
  EOSBTC = 'EOSBTC',
  SNTBTC = 'SNTBTC',
  ETCETH = 'ETCETH',
  ETCBTC = 'ETCBTC',
  MTHBTC = 'MTHBTC',
  MTHETH = 'MTHETH',
  ENGBTC = 'ENGBTC',
  ENGETH = 'ENGETH',
  DNTBTC = 'DNTBTC',
  ZECBTC = 'ZECBTC',
  ZECETH = 'ZECETH',
  BNTBTC = 'BNTBTC',
  ASTBTC = 'ASTBTC',
  ASTETH = 'ASTETH',
  DASHBTC = 'DASHBTC',
  DASHETH = 'DASHETH',
  OAXBTC = 'OAXBTC',
  ICNBTC = 'ICNBTC',
  BTGBTC = 'BTGBTC',
  BTGETH = 'BTGETH',
  EVXBTC = 'EVXBTC',
  EVXETH = 'EVXETH',
  REQBTC = 'REQBTC',
  REQETH = 'REQETH',
  VIBBTC = 'VIBBTC',
  VIBETH = 'VIBETH',
  HSRETH = 'HSRETH',
  TRXBTC = 'TRXBTC',
  TRXETH = 'TRXETH',
  POWRBTC = 'POWRBTC',
  POWRETH = 'POWRETH',
  ARKBTC = 'ARKBTC',
  ARKETH = 'ARKETH',
  YOYOETH = 'YOYOETH',
  XRPBTC = 'XRPBTC',
  XRPETH = 'XRPETH',
  MODBTC = 'MODBTC',
  MODETH = 'MODETH',
  ENJBTC = 'ENJBTC',
  ENJETH = 'ENJETH',
  STORJBTC = 'STORJBTC',
  STORJETH = 'STORJETH',
  BNBUSDT = 'BNBUSDT',
  VENBNB = 'VENBNB',
  YOYOBNB = 'YOYOBNB',
  POWRBNB = 'POWRBNB',
  VENBTC = 'VENBTC',
  VENETH = 'VENETH',
  KMDBTC = 'KMDBTC',
  KMDETH = 'KMDETH',
  NULSBNB = 'NULSBNB',
  RCNBTC = 'RCNBTC',
  RCNETH = 'RCNETH',
  RCNBNB = 'RCNBNB',
  NULSBTC = 'NULSBTC',
  NULSETH = 'NULSETH',
  RDNBTC = 'RDNBTC',
  RDNETH = 'RDNETH',
  RDNBNB = 'RDNBNB',
  XMRBTC = 'XMRBTC',
  XMRETH = 'XMRETH',
  DLTBNB = 'DLTBNB',
  WTCBNB = 'WTCBNB',
  DLTBTC = 'DLTBTC',
  DLTETH = 'DLTETH',
  AMBBTC = 'AMBBTC',
  AMBETH = 'AMBETH',
  AMBBNB = 'AMBBNB',
  BCCETH = 'BCCETH',
  BCCUSDT = 'BCCUSDT',
  BCCBNB = 'BCCBNB',
  BATBTC = 'BATBTC',
  BATETH = 'BATETH',
  BATBNB = 'BATBNB',
  BCPTBTC = 'BCPTBTC',
  BCPTETH = 'BCPTETH',
  BCPTBNB = 'BCPTBNB',
  ARNBTC = 'ARNBTC',
  ARNETH = 'ARNETH',
  GVTBTC = 'GVTBTC',
  GVTETH = 'GVTETH',
  CDTBTC = 'CDTBTC',
  CDTETH = 'CDTETH',
  GXSBTC = 'GXSBTC',
  GXSETH = 'GXSETH',
  NEOUSDT = 'NEOUSDT',
  NEOBNB = 'NEOBNB',
  POEBTC = 'POEBTC',
  POEETH = 'POEETH',
  QSPBTC = 'QSPBTC',
  QSPETH = 'QSPETH',
  QSPBNB = 'QSPBNB',
  BTSBTC = 'BTSBTC',
  BTSETH = 'BTSETH',
  BTSBNB = 'BTSBNB',
  XZCBTC = 'XZCBTC',
  XZCETH = 'XZCETH',
  XZCBNB = 'XZCBNB',
  LSKBTC = 'LSKBTC',
  LSKETH = 'LSKETH',
  LSKBNB = 'LSKBNB',
  TNTBTC = 'TNTBTC',
  TNTETH = 'TNTETH',
  FUELBTC = 'FUELBTC',
  FUELETH = 'FUELETH',
  MANABTC = 'MANABTC',
  MANAETH = 'MANAETH',
  BCDBTC = 'BCDBTC',
  BCDETH = 'BCDETH',
  DGDBTC = 'DGDBTC',
  DGDETH = 'DGDETH',
  IOTABNB = 'IOTABNB',
  ADXBTC = 'ADXBTC',
  ADXETH = 'ADXETH',
  ADXBNB = 'ADXBNB',
  ADABTC = 'ADABTC',
  ADAETH = 'ADAETH',
  PPTBTC = 'PPTBTC',
  PPTETH = 'PPTETH',
  CMTBTC = 'CMTBTC',
  CMTETH = 'CMTETH',
  CMTBNB = 'CMTBNB',
  XLMBTC = 'XLMBTC',
  XLMETH = 'XLMETH',
  XLMBNB = 'XLMBNB',
  CNDBTC = 'CNDBTC',
  CNDETH = 'CNDETH',
  CNDBNB = 'CNDBNB',
  LENDBTC = 'LENDBTC',
  LENDETH = 'LENDETH',
  WABIBTC = 'WABIBTC',
  WABIETH = 'WABIETH',
  WABIBNB = 'WABIBNB',
  LTCETH = 'LTCETH',
  LTCUSDT = 'LTCUSDT',
  LTCBNB = 'LTCBNB',
  TNBBTC = 'TNBBTC',
  TNBETH = 'TNBETH',
  WAVESBTC = 'WAVESBTC',
  WAVESETH = 'WAVESETH',
  WAVESBNB = 'WAVESBNB',
  GTOBTC = 'GTOBTC',
  GTOETH = 'GTOETH',
  GTOBNB = 'GTOBNB',
  ICXBTC = 'ICXBTC',
  ICXETH = 'ICXETH',
  ICXBNB = 'ICXBNB',
  OSTBTC = 'OSTBTC',
  OSTETH = 'OSTETH',
  OSTBNB = 'OSTBNB',
  ELFBTC = 'ELFBTC',
  ELFETH = 'ELFETH',
  AIONBTC = 'AIONBTC',
  AIONETH = 'AIONETH',
  AIONBNB = 'AIONBNB',
  NEBLBTC = 'NEBLBTC',
  NEBLETH = 'NEBLETH',
  NEBLBNB = 'NEBLBNB',
  BRDBTC = 'BRDBTC',
  BRDETH = 'BRDETH',
  BRDBNB = 'BRDBNB',
  MCOBNB = 'MCOBNB',
  EDOBTC = 'EDOBTC',
  EDOETH = 'EDOETH',
  WINGSBTC = 'WINGSBTC',
  WINGSETH = 'WINGSETH',
  NAVBTC = 'NAVBTC',
  NAVETH = 'NAVETH',
  NAVBNB = 'NAVBNB',
  LUNBTC = 'LUNBTC',
  LUNETH = 'LUNETH',
  TRIGBTC = 'TRIGBTC',
  TRIGETH = 'TRIGETH',
  TRIGBNB = 'TRIGBNB',
  APPCBTC = 'APPCBTC',
  APPCETH = 'APPCETH',
  APPCBNB = 'APPCBNB',
  VIBEBTC = 'VIBEBTC',
  VIBEETH = 'VIBEETH',
  RLCBTC = 'RLCBTC',
  RLCETH = 'RLCETH',
  RLCBNB = 'RLCBNB',
  INSBTC = 'INSBTC',
  INSETH = 'INSETH',
  PIVXBTC = 'PIVXBTC',
  PIVXETH = 'PIVXETH',
  PIVXBNB = 'PIVXBNB',
  IOSTBTC = 'IOSTBTC',
  IOSTETH = 'IOSTETH',
  CHATBTC = 'CHATBTC',
  CHATETH = 'CHATETH',
  STEEMBTC = 'STEEMBTC',
  STEEMETH = 'STEEMETH',
  STEEMBNB = 'STEEMBNB',
  NANOBTC = 'NANOBTC',
  NANOETH = 'NANOETH',
  NANOBNB = 'NANOBNB',
  VIABTC = 'VIABTC',
  VIAETH = 'VIAETH',
  VIABNB = 'VIABNB',
  BLZBTC = 'BLZBTC',
  BLZETH = 'BLZETH',
  BLZBNB = 'BLZBNB',
  AEBTC = 'AEBTC',
  AEETH = 'AEETH',
  AEBNB = 'AEBNB',
  RPXBTC = 'RPXBTC',
  RPXETH = 'RPXETH',
  RPXBNB = 'RPXBNB',
  NCASHBTC = 'NCASHBTC',
  NCASHETH = 'NCASHETH',
  NCASHBNB = 'NCASHBNB',
  POABTC = 'POABTC',
  POAETH = 'POAETH',
  POABNB = 'POABNB',
  ZILBTC = 'ZILBTC',
  ZILETH = 'ZILETH',
  ZILBNB = 'ZILBNB',
  ONTBTC = 'ONTBTC',
  ONTETH = 'ONTETH',
  ONTBNB = 'ONTBNB',
  STORMBTC = 'STORMBTC',
  STORMETH = 'STORMETH',
  STORMBNB = 'STORMBNB',
  QTUMBNB = 'QTUMBNB',
  QTUMUSDT = 'QTUMUSDT',
  XEMBTC = 'XEMBTC',
  XEMETH = 'XEMETH',
  XEMBNB = 'XEMBNB',
  WANBTC = 'WANBTC',
  WANETH = 'WANETH',
  WANBNB = 'WANBNB',
  WPRBTC = 'WPRBTC',
  WPRETH = 'WPRETH',
  QLCBTC = 'QLCBTC',
  QLCETH = 'QLCETH',
  SYSBTC = 'SYSBTC',
  SYSETH = 'SYSETH',
  SYSBNB = 'SYSBNB',
  QLCBNB = 'QLCBNB',
  GRSBTC = 'GRSBTC',
  GRSETH = 'GRSETH',
  ADAUSDT = 'ADAUSDT',
  ADABNB = 'ADABNB',
  CLOAKBTC = 'CLOAKBTC',
  CLOAKETH = 'CLOAKETH',
  GNTBTC = 'GNTBTC',
  GNTETH = 'GNTETH',
  GNTBNB = 'GNTBNB',
  LOOMBTC = 'LOOMBTC',
  LOOMETH = 'LOOMETH',
  LOOMBNB = 'LOOMBNB',
  XRPUSDT = 'XRPUSDT',
  BCNBTC = 'BCNBTC',
  BCNETH = 'BCNETH',
  BCNBNB = 'BCNBNB',
  REPBTC = 'REPBTC',
  REPETH = 'REPETH',
  REPBNB = 'REPBNB',
  BTCTUSD = 'BTCTUSD',
  TUSDBTC = 'TUSDBTC',
  ETHTUSD = 'ETHTUSD',
  TUSDETH = 'TUSDETH',
  TUSDBNB = 'TUSDBNB',
  ZENBTC = 'ZENBTC',
  ZENETH = 'ZENETH',
  ZENBNB = 'ZENBNB',
  SKYBTC = 'SKYBTC',
  SKYETH = 'SKYETH',
  SKYBNB = 'SKYBNB',
  EOSUSDT = 'EOSUSDT',
  EOSBNB = 'EOSBNB',
  CVCBTC = 'CVCBTC',
  CVCETH = 'CVCETH',
  CVCBNB = 'CVCBNB',
  THETABTC = 'THETABTC',
  THETAETH = 'THETAETH',
  THETABNB = 'THETABNB',
  XRPBNB = 'XRPBNB',
  TUSDUSDT = 'TUSDUSDT',
  IOTAUSDT = 'IOTAUSDT',
  XLMUSDT = 'XLMUSDT',
  IOTXBTC = 'IOTXBTC',
  IOTXETH = 'IOTXETH',
  QKCBTC = 'QKCBTC',
  QKCETH = 'QKCETH',
  AGIBTC = 'AGIBTC',
  AGIETH = 'AGIETH',
  AGIBNB = 'AGIBNB',
  NXSBTC = 'NXSBTC',
  NXSETH = 'NXSETH',
  NXSBNB = 'NXSBNB',
  ENJBNB = 'ENJBNB',
  DATABTC = 'DATABTC',
  DATAETH = 'DATAETH',
  ONTUSDT = 'ONTUSDT',
  TRXBNB = 'TRXBNB',
  TRXUSDT = 'TRXUSDT',
  ETCUSDT = 'ETCUSDT',
  ETCBNB = 'ETCBNB',
  ICXUSDT = 'ICXUSDT',
  SCBTC = 'SCBTC',
  SCETH = 'SCETH',
  SCBNB = 'SCBNB',
  NPXSBTC = 'NPXSBTC',
  NPXSETH = 'NPXSETH',
  VENUSDT = 'VENUSDT',
  KEYBTC = 'KEYBTC',
  KEYETH = 'KEYETH',
  NASBTC = 'NASBTC',
  NASETH = 'NASETH',
  NASBNB = 'NASBNB',
  MFTBTC = 'MFTBTC',
  MFTETH = 'MFTETH',
  MFTBNB = 'MFTBNB',
  DENTBTC = 'DENTBTC',
  DENTETH = 'DENTETH',
  ARDRBTC = 'ARDRBTC',
  ARDRETH = 'ARDRETH',
  ARDRBNB = 'ARDRBNB',
  NULSUSDT = 'NULSUSDT',
  HOTBTC = 'HOTBTC',
  HOTETH = 'HOTETH',
  VETBTC = 'VETBTC',
  VETETH = 'VETETH',
  VETUSDT = 'VETUSDT',
  VETBNB = 'VETBNB',
  DOCKBTC = 'DOCKBTC',
  DOCKETH = 'DOCKETH',
  POLYBTC = 'POLYBTC',
  POLYBNB = 'POLYBNB',
  PHXBTC = 'PHXBTC',
  PHXETH = 'PHXETH',
  PHXBNB = 'PHXBNB',
  HCBTC = 'HCBTC',
  HCETH = 'HCETH',
  GOBTC = 'GOBTC',
  GOBNB = 'GOBNB',
  PAXBTC = 'PAXBTC',
  PAXBNB = 'PAXBNB',
  PAXUSDT = 'PAXUSDT',
  PAXETH = 'PAXETH',
  RVNBTC = 'RVNBTC',
  RVNBNB = 'RVNBNB',
  DCRBTC = 'DCRBTC',
  DCRBNB = 'DCRBNB',
  USDCBNB = 'USDCBNB',
  MITHBTC = 'MITHBTC',
  MITHBNB = 'MITHBNB',
  BCHABCBTC = 'BCHABCBTC',
  BCHSVBTC = 'BCHSVBTC',
  BCHABCUSDT = 'BCHABCUSDT',
  BCHSVUSDT = 'BCHSVUSDT',
  BNBPAX = 'BNBPAX',
  BTCPAX = 'BTCPAX',
  ETHPAX = 'ETHPAX',
  XRPPAX = 'XRPPAX',
  EOSPAX = 'EOSPAX',
  XLMPAX = 'XLMPAX',
  RENBTC = 'RENBTC',
  RENBNB = 'RENBNB',
  BNBTUSD = 'BNBTUSD',
  XRPTUSD = 'XRPTUSD',
  EOSTUSD = 'EOSTUSD',
  XLMTUSD = 'XLMTUSD',
  BNBUSDC = 'BNBUSDC',
  BTCUSDC = 'BTCUSDC',
  ETHUSDC = 'ETHUSDC',
  XRPUSDC = 'XRPUSDC',
  EOSUSDC = 'EOSUSDC',
  XLMUSDC = 'XLMUSDC',
  USDCUSDT = 'USDCUSDT',
  ADATUSD = 'ADATUSD',
  TRXTUSD = 'TRXTUSD',
  NEOTUSD = 'NEOTUSD',
  TRXXRP = 'TRXXRP',
  XZCXRP = 'XZCXRP',
  PAXTUSD = 'PAXTUSD',
  USDCTUSD = 'USDCTUSD',
  USDCPAX = 'USDCPAX',
  LINKUSDT = 'LINKUSDT',
  LINKTUSD = 'LINKTUSD',
  LINKPAX = 'LINKPAX',
  LINKUSDC = 'LINKUSDC',
  WAVESUSDT = 'WAVESUSDT',
  WAVESTUSD = 'WAVESTUSD',
  WAVESPAX = 'WAVESPAX',
  WAVESUSDC = 'WAVESUSDC',
  BCHABCTUSD = 'BCHABCTUSD',
  BCHABCPAX = 'BCHABCPAX',
  BCHABCUSDC = 'BCHABCUSDC',
  BCHSVTUSD = 'BCHSVTUSD',
  BCHSVPAX = 'BCHSVPAX',
  BCHSVUSDC = 'BCHSVUSDC',
  LTCTUSD = 'LTCTUSD',
  LTCPAX = 'LTCPAX',
  LTCUSDC = 'LTCUSDC',
  TRXPAX = 'TRXPAX',
  TRXUSDC = 'TRXUSDC',
  BTTBTC = 'BTTBTC',
  BTTBNB = 'BTTBNB',
  BTTUSDT = 'BTTUSDT',
  BNBUSDS = 'BNBUSDS',
  BTCUSDS = 'BTCUSDS',
  USDSUSDT = 'USDSUSDT',
  USDSPAX = 'USDSPAX',
  USDSTUSD = 'USDSTUSD',
  USDSUSDC = 'USDSUSDC',
  BTTPAX = 'BTTPAX',
  BTTTUSD = 'BTTTUSD',
  BTTUSDC = 'BTTUSDC',
  ONGBNB = 'ONGBNB',
  ONGBTC = 'ONGBTC',
  ONGUSDT = 'ONGUSDT',
  HOTBNB = 'HOTBNB',
  HOTUSDT = 'HOTUSDT',
  ZILUSDT = 'ZILUSDT',
  ZRXBNB = 'ZRXBNB',
  ZRXUSDT = 'ZRXUSDT',
  FETBNB = 'FETBNB',
  FETBTC = 'FETBTC',
  FETUSDT = 'FETUSDT',
  BATUSDT = 'BATUSDT',
  XMRBNB = 'XMRBNB',
  XMRUSDT = 'XMRUSDT',
  ZECBNB = 'ZECBNB',
  ZECUSDT = 'ZECUSDT',
  ZECPAX = 'ZECPAX',
  ZECTUSD = 'ZECTUSD',
  ZECUSDC = 'ZECUSDC',
  IOSTBNB = 'IOSTBNB',
  IOSTUSDT = 'IOSTUSDT',
  CELRBNB = 'CELRBNB',
  CELRBTC = 'CELRBTC',
  CELRUSDT = 'CELRUSDT',
  ADAPAX = 'ADAPAX',
  ADAUSDC = 'ADAUSDC',
  NEOPAX = 'NEOPAX',
  NEOUSDC = 'NEOUSDC',
  DASHBNB = 'DASHBNB',
  DASHUSDT = 'DASHUSDT',
  NANOUSDT = 'NANOUSDT',
  OMGBNB = 'OMGBNB',
  OMGUSDT = 'OMGUSDT',
  THETAUSDT = 'THETAUSDT',
  ENJUSDT = 'ENJUSDT',
  MITHUSDT = 'MITHUSDT',
  MATICBNB = 'MATICBNB',
  MATICBTC = 'MATICBTC',
  MATICUSDT = 'MATICUSDT',
  ATOMBNB = 'ATOMBNB',
  ATOMBTC = 'ATOMBTC',
  ATOMUSDT = 'ATOMUSDT',
  ATOMUSDC = 'ATOMUSDC',
  ATOMPAX = 'ATOMPAX',
  ATOMTUSD = 'ATOMTUSD',
  ETCUSDC = 'ETCUSDC',
  ETCPAX = 'ETCPAX',
  ETCTUSD = 'ETCTUSD',
  BATUSDC = 'BATUSDC',
  BATPAX = 'BATPAX',
  BATTUSD = 'BATTUSD',
  PHBBNB = 'PHBBNB',
  PHBBTC = 'PHBBTC',
  PHBUSDC = 'PHBUSDC',
  PHBTUSD = 'PHBTUSD',
  PHBPAX = 'PHBPAX',
  TFUELBNB = 'TFUELBNB',
  TFUELBTC = 'TFUELBTC',
  TFUELUSDT = 'TFUELUSDT',
  TFUELUSDC = 'TFUELUSDC',
  TFUELTUSD = 'TFUELTUSD',
  TFUELPAX = 'TFUELPAX',
  ONEBNB = 'ONEBNB',
  ONEBTC = 'ONEBTC',
  ONEUSDT = 'ONEUSDT',
  ONETUSD = 'ONETUSD',
  ONEPAX = 'ONEPAX',
  ONEUSDC = 'ONEUSDC',
  FTMBNB = 'FTMBNB',
  FTMBTC = 'FTMBTC',
  FTMUSDT = 'FTMUSDT',
  FTMTUSD = 'FTMTUSD',
  FTMPAX = 'FTMPAX',
  FTMUSDC = 'FTMUSDC',
  BTCBBTC = 'BTCBBTC',
  BCPTTUSD = 'BCPTTUSD',
  BCPTPAX = 'BCPTPAX',
  BCPTUSDC = 'BCPTUSDC',
  ALGOBNB = 'ALGOBNB',
  ALGOBTC = 'ALGOBTC',
  ALGOUSDT = 'ALGOUSDT',
  ALGOTUSD = 'ALGOTUSD',
  ALGOPAX = 'ALGOPAX',
  ALGOUSDC = 'ALGOUSDC',
  USDSBUSDT = 'USDSBUSDT',
  USDSBUSDS = 'USDSBUSDS',
  GTOUSDT = 'GTOUSDT',
  GTOPAX = 'GTOPAX',
  GTOTUSD = 'GTOTUSD',
  GTOUSDC = 'GTOUSDC',
  ERDBNB = 'ERDBNB',
  ERDBTC = 'ERDBTC',
  ERDUSDT = 'ERDUSDT',
  ERDPAX = 'ERDPAX',
  ERDUSDC = 'ERDUSDC',
  DOGEBNB = 'DOGEBNB',
  DOGEBTC = 'DOGEBTC',
  DOGEUSDT = 'DOGEUSDT',
  DOGEPAX = 'DOGEPAX',
  DOGEUSDC = 'DOGEUSDC',
  DUSKBNB = 'DUSKBNB',
  DUSKBTC = 'DUSKBTC',
  DUSKUSDT = 'DUSKUSDT',
  DUSKUSDC = 'DUSKUSDC',
  DUSKPAX = 'DUSKPAX',
  BGBPUSDC = 'BGBPUSDC',
  ANKRBNB = 'ANKRBNB',
  ANKRBTC = 'ANKRBTC',
  ANKRUSDT = 'ANKRUSDT',
  ANKRTUSD = 'ANKRTUSD',
  ANKRPAX = 'ANKRPAX',
  ANKRUSDC = 'ANKRUSDC',
  ONTPAX = 'ONTPAX',
  ONTUSDC = 'ONTUSDC',
  WINBNB = 'WINBNB',
  WINBTC = 'WINBTC',
  WINUSDT = 'WINUSDT',
  WINUSDC = 'WINUSDC',
  COSBNB = 'COSBNB',
  COSBTC = 'COSBTC',
  COSUSDT = 'COSUSDT',
  TUSDBTUSD = 'TUSDBTUSD',
  NPXSUSDT = 'NPXSUSDT',
  NPXSUSDC = 'NPXSUSDC',
  COCOSBNB = 'COCOSBNB',
  COCOSBTC = 'COCOSBTC',
  COCOSUSDT = 'COCOSUSDT',
  MTLUSDT = 'MTLUSDT',
  TOMOBNB = 'TOMOBNB',
  TOMOBTC = 'TOMOBTC',
  TOMOUSDT = 'TOMOUSDT',
  TOMOUSDC = 'TOMOUSDC',
  PERLBNB = 'PERLBNB',
  PERLBTC = 'PERLBTC',
  PERLUSDC = 'PERLUSDC',
  PERLUSDT = 'PERLUSDT',
  DENTUSDT = 'DENTUSDT',
  MFTUSDT = 'MFTUSDT',
  KEYUSDT = 'KEYUSDT',
  STORMUSDT = 'STORMUSDT',
  DOCKUSDT = 'DOCKUSDT',
  WANUSDT = 'WANUSDT',
  FUNUSDT = 'FUNUSDT',
  CVCUSDT = 'CVCUSDT',
  BTTTRX = 'BTTTRX',
  WINTRX = 'WINTRX',
  CHZBNB = 'CHZBNB',
  CHZBTC = 'CHZBTC',
  CHZUSDT = 'CHZUSDT',
  BANDBNB = 'BANDBNB',
  BANDBTC = 'BANDBTC',
  BANDUSDT = 'BANDUSDT',
  BNBBUSD = 'BNBBUSD',
  BTCBUSD = 'BTCBUSD',
  BUSDUSDT = 'BUSDUSDT',
  BEAMBNB = 'BEAMBNB',
  BEAMBTC = 'BEAMBTC',
  BEAMUSDT = 'BEAMUSDT',
  XTZBNB = 'XTZBNB',
  XTZBTC = 'XTZBTC',
  XTZUSDT = 'XTZUSDT',
  RENUSDT = 'RENUSDT',
  RVNUSDT = 'RVNUSDT',
  HCUSDT = 'HCUSDT',
  HBARBNB = 'HBARBNB',
  HBARBTC = 'HBARBTC',
  HBARUSDT = 'HBARUSDT',
  NKNBNB = 'NKNBNB',
  NKNBTC = 'NKNBTC',
  NKNUSDT = 'NKNUSDT',
  XRPBUSD = 'XRPBUSD',
  ETHBUSD = 'ETHBUSD',
  BCHABCBUSD = 'BCHABCBUSD',
  LTCBUSD = 'LTCBUSD',
  LINKBUSD = 'LINKBUSD',
  ETCBUSD = 'ETCBUSD',
  STXBNB = 'STXBNB',
  STXBTC = 'STXBTC',
  STXUSDT = 'STXUSDT',
  KAVABNB = 'KAVABNB',
  KAVABTC = 'KAVABTC',
  KAVAUSDT = 'KAVAUSDT',
  BUSDNGN = 'BUSDNGN',
  BNBNGN = 'BNBNGN',
  BTCNGN = 'BTCNGN',
  ARPABNB = 'ARPABNB',
  ARPABTC = 'ARPABTC',
  ARPAUSDT = 'ARPAUSDT',
  TRXBUSD = 'TRXBUSD',
  EOSBUSD = 'EOSBUSD',
  IOTXUSDT = 'IOTXUSDT',
  RLCUSDT = 'RLCUSDT',
  MCOUSDT = 'MCOUSDT',
  XLMBUSD = 'XLMBUSD',
  ADABUSD = 'ADABUSD',
  CTXCBNB = 'CTXCBNB',
  CTXCBTC = 'CTXCBTC',
  CTXCUSDT = 'CTXCUSDT',
  BCHBNB = 'BCHBNB',
  BCHBTC = 'BCHBTC',
  BCHUSDT = 'BCHUSDT',
  BCHUSDC = 'BCHUSDC',
  BCHTUSD = 'BCHTUSD',
  BCHPAX = 'BCHPAX',
  BCHBUSD = 'BCHBUSD',
  BTCRUB = 'BTCRUB',
  ETHRUB = 'ETHRUB',
  XRPRUB = 'XRPRUB',
  BNBRUB = 'BNBRUB',
  TROYBNB = 'TROYBNB',
  TROYBTC = 'TROYBTC',
  TROYUSDT = 'TROYUSDT',
  BUSDRUB = 'BUSDRUB',
  QTUMBUSD = 'QTUMBUSD',
  VETBUSD = 'VETBUSD',
  VITEBNB = 'VITEBNB',
  VITEBTC = 'VITEBTC',
  VITEUSDT = 'VITEUSDT',
  FTTBNB = 'FTTBNB',
  FTTBTC = 'FTTBTC',
  FTTUSDT = 'FTTUSDT',
  BTCTRY = 'BTCTRY',
  BNBTRY = 'BNBTRY',
  BUSDTRY = 'BUSDTRY',
  ETHTRY = 'ETHTRY',
  XRPTRY = 'XRPTRY',
  USDTTRY = 'USDTTRY',
  USDTRUB = 'USDTRUB',
  BTCEUR = 'BTCEUR',
  ETHEUR = 'ETHEUR',
  BNBEUR = 'BNBEUR',
  XRPEUR = 'XRPEUR',
  EURBUSD = 'EURBUSD',
  EURUSDT = 'EURUSDT',
  OGNBNB = 'OGNBNB',
  OGNBTC = 'OGNBTC',
  OGNUSDT = 'OGNUSDT',
  DREPBNB = 'DREPBNB',
  DREPBTC = 'DREPBTC',
  DREPUSDT = 'DREPUSDT',
  BULLUSDT = 'BULLUSDT',
  BULLBUSD = 'BULLBUSD',
  BEARUSDT = 'BEARUSDT',
  BEARBUSD = 'BEARBUSD',
  ETHBULLUSDT = 'ETHBULLUSDT',
  ETHBULLBUSD = 'ETHBULLBUSD',
  ETHBEARUSDT = 'ETHBEARUSDT',
  ETHBEARBUSD = 'ETHBEARBUSD',
  TCTBNB = 'TCTBNB',
  TCTBTC = 'TCTBTC',
  TCTUSDT = 'TCTUSDT',
  WRXBNB = 'WRXBNB',
  WRXBTC = 'WRXBTC',
  WRXUSDT = 'WRXUSDT',
  ICXBUSD = 'ICXBUSD',
  BTSUSDT = 'BTSUSDT',
  BTSBUSD = 'BTSBUSD',
  LSKUSDT = 'LSKUSDT',
  BNTUSDT = 'BNTUSDT',
  BNTBUSD = 'BNTBUSD',
  LTOBNB = 'LTOBNB',
  LTOBTC = 'LTOBTC',
  LTOUSDT = 'LTOUSDT',
  ATOMBUSD = 'ATOMBUSD',
  DASHBUSD = 'DASHBUSD',
  NEOBUSD = 'NEOBUSD',
  WAVESBUSD = 'WAVESBUSD',
  XTZBUSD = 'XTZBUSD',
  EOSBULLUSDT = 'EOSBULLUSDT',
  EOSBULLBUSD = 'EOSBULLBUSD',
  EOSBEARUSDT = 'EOSBEARUSDT',
  EOSBEARBUSD = 'EOSBEARBUSD',
  XRPBULLUSDT = 'XRPBULLUSDT',
  XRPBULLBUSD = 'XRPBULLBUSD',
  XRPBEARUSDT = 'XRPBEARUSDT',
  XRPBEARBUSD = 'XRPBEARBUSD',
  BATBUSD = 'BATBUSD',
  ENJBUSD = 'ENJBUSD',
  NANOBUSD = 'NANOBUSD',
  ONTBUSD = 'ONTBUSD',
  RVNBUSD = 'RVNBUSD',
  STRATBUSD = 'STRATBUSD',
  STRATBNB = 'STRATBNB',
  STRATUSDT = 'STRATUSDT',
  AIONBUSD = 'AIONBUSD',
  AIONUSDT = 'AIONUSDT',
  MBLBNB = 'MBLBNB',
  MBLBTC = 'MBLBTC',
  MBLUSDT = 'MBLUSDT',
  COTIBNB = 'COTIBNB',
  COTIBTC = 'COTIBTC',
  COTIUSDT = 'COTIUSDT',
  ALGOBUSD = 'ALGOBUSD',
  BTTBUSD = 'BTTBUSD',
  TOMOBUSD = 'TOMOBUSD',
  XMRBUSD = 'XMRBUSD',
  ZECBUSD = 'ZECBUSD',
  BNBBULLUSDT = 'BNBBULLUSDT',
  BNBBULLBUSD = 'BNBBULLBUSD',
  BNBBEARUSDT = 'BNBBEARUSDT',
  BNBBEARBUSD = 'BNBBEARBUSD',
  STPTBNB = 'STPTBNB',
  STPTBTC = 'STPTBTC',
  STPTUSDT = 'STPTUSDT',
  BTCZAR = 'BTCZAR',
  ETHZAR = 'ETHZAR',
  BNBZAR = 'BNBZAR',
  USDTZAR = 'USDTZAR',
  BUSDZAR = 'BUSDZAR',
  BTCBKRW = 'BTCBKRW',
  ETHBKRW = 'ETHBKRW',
  BNBBKRW = 'BNBBKRW',
  WTCUSDT = 'WTCUSDT',
  DATABUSD = 'DATABUSD',
  DATAUSDT = 'DATAUSDT',
  XZCUSDT = 'XZCUSDT',
  SOLBNB = 'SOLBNB',
  SOLBTC = 'SOLBTC',
  SOLBUSD = 'SOLBUSD',
  BTCIDRT = 'BTCIDRT',
  BNBIDRT = 'BNBIDRT',
  USDTIDRT = 'USDTIDRT',
  BUSDIDRT = 'BUSDIDRT',
  CTSIBTC = 'CTSIBTC',
  CTSIUSDT = 'CTSIUSDT',
  CTSIBNB = 'CTSIBNB',
  CTSIBUSD = 'CTSIBUSD',
  HIVEBNB = 'HIVEBNB',
  HIVEBTC = 'HIVEBTC',
  HIVEUSDT = 'HIVEUSDT',
  CHRBNB = 'CHRBNB',
  CHRBTC = 'CHRBTC',
  CHRUSDT = 'CHRUSDT',
  BTCUPUSDT = 'BTCUPUSDT',
  BTCDOWNUSDT = 'BTCDOWNUSDT',
  GXSUSDT = 'GXSUSDT',
  ARDRUSDT = 'ARDRUSDT',
  ERDBUSD = 'ERDBUSD',
  LENDUSDT = 'LENDUSDT',
  HBARBUSD = 'HBARBUSD',
  MATICBUSD = 'MATICBUSD',
  WRXBUSD = 'WRXBUSD',
  ZILBUSD = 'ZILBUSD',
}

export enum Exchange {
  BINANCE = 'BINANCE',
}

export const pairMap = {
  [Exchange.BINANCE]: {
    [Pair.ETHBTC]: 'ethbtc',
    [Pair.LTCBTC]: 'ltcbtc',
    [Pair.BNBBTC]: 'bnbbtc',
    [Pair.NEOBTC]: 'neobtc',
    [Pair.QTUMETH]: 'qtumeth',
    [Pair.EOSETH]: 'eoseth',
    [Pair.SNTETH]: 'snteth',
    [Pair.BNTETH]: 'bnteth',
    [Pair.BCCBTC]: 'bccbtc',
    [Pair.GASBTC]: 'gasbtc',
    [Pair.BNBETH]: 'bnbeth',
    [Pair.BTCUSDT]: 'btcusdt',
    [Pair.ETHUSDT]: 'ethusdt',
    [Pair.HSRBTC]: 'hsrbtc',
    [Pair.OAXETH]: 'oaxeth',
    [Pair.DNTETH]: 'dnteth',
    [Pair.MCOETH]: 'mcoeth',
    [Pair.ICNETH]: 'icneth',
    [Pair.MCOBTC]: 'mcobtc',
    [Pair.WTCBTC]: 'wtcbtc',
    [Pair.WTCETH]: 'wtceth',
    [Pair.LRCBTC]: 'lrcbtc',
    [Pair.LRCETH]: 'lrceth',
    [Pair.QTUMBTC]: 'qtumbtc',
    [Pair.YOYOBTC]: 'yoyobtc',
    [Pair.OMGBTC]: 'omgbtc',
    [Pair.OMGETH]: 'omgeth',
    [Pair.ZRXBTC]: 'zrxbtc',
    [Pair.ZRXETH]: 'zrxeth',
    [Pair.STRATBTC]: 'stratbtc',
    [Pair.STRATETH]: 'strateth',
    [Pair.SNGLSBTC]: 'snglsbtc',
    [Pair.SNGLSETH]: 'snglseth',
    [Pair.BQXBTC]: 'bqxbtc',
    [Pair.BQXETH]: 'bqxeth',
    [Pair.KNCBTC]: 'kncbtc',
    [Pair.KNCETH]: 'knceth',
    [Pair.FUNBTC]: 'funbtc',
    [Pair.FUNETH]: 'funeth',
    [Pair.SNMBTC]: 'snmbtc',
    [Pair.SNMETH]: 'snmeth',
    [Pair.NEOETH]: 'neoeth',
    [Pair.IOTABTC]: 'iotabtc',
    [Pair.IOTAETH]: 'iotaeth',
    [Pair.LINKBTC]: 'linkbtc',
    [Pair.LINKETH]: 'linketh',
    [Pair.XVGBTC]: 'xvgbtc',
    [Pair.XVGETH]: 'xvgeth',
    [Pair.SALTBTC]: 'saltbtc',
    [Pair.SALTETH]: 'salteth',
    [Pair.MDABTC]: 'mdabtc',
    [Pair.MDAETH]: 'mdaeth',
    [Pair.MTLBTC]: 'mtlbtc',
    [Pair.MTLETH]: 'mtleth',
    [Pair.SUBBTC]: 'subbtc',
    [Pair.SUBETH]: 'subeth',
    [Pair.EOSBTC]: 'eosbtc',
    [Pair.SNTBTC]: 'sntbtc',
    [Pair.ETCETH]: 'etceth',
    [Pair.ETCBTC]: 'etcbtc',
    [Pair.MTHBTC]: 'mthbtc',
    [Pair.MTHETH]: 'mtheth',
    [Pair.ENGBTC]: 'engbtc',
    [Pair.ENGETH]: 'engeth',
    [Pair.DNTBTC]: 'dntbtc',
    [Pair.ZECBTC]: 'zecbtc',
    [Pair.ZECETH]: 'zeceth',
    [Pair.BNTBTC]: 'bntbtc',
    [Pair.ASTBTC]: 'astbtc',
    [Pair.ASTETH]: 'asteth',
    [Pair.DASHBTC]: 'dashbtc',
    [Pair.DASHETH]: 'dasheth',
    [Pair.OAXBTC]: 'oaxbtc',
    [Pair.ICNBTC]: 'icnbtc',
    [Pair.BTGBTC]: 'btgbtc',
    [Pair.BTGETH]: 'btgeth',
    [Pair.EVXBTC]: 'evxbtc',
    [Pair.EVXETH]: 'evxeth',
    [Pair.REQBTC]: 'reqbtc',
    [Pair.REQETH]: 'reqeth',
    [Pair.VIBBTC]: 'vibbtc',
    [Pair.VIBETH]: 'vibeth',
    [Pair.HSRETH]: 'hsreth',
    [Pair.TRXBTC]: 'trxbtc',
    [Pair.TRXETH]: 'trxeth',
    [Pair.POWRBTC]: 'powrbtc',
    [Pair.POWRETH]: 'powreth',
    [Pair.ARKBTC]: 'arkbtc',
    [Pair.ARKETH]: 'arketh',
    [Pair.YOYOETH]: 'yoyoeth',
    [Pair.XRPBTC]: 'xrpbtc',
    [Pair.XRPETH]: 'xrpeth',
    [Pair.MODBTC]: 'modbtc',
    [Pair.MODETH]: 'modeth',
    [Pair.ENJBTC]: 'enjbtc',
    [Pair.ENJETH]: 'enjeth',
    [Pair.STORJBTC]: 'storjbtc',
    [Pair.STORJETH]: 'storjeth',
    [Pair.BNBUSDT]: 'bnbusdt',
    [Pair.VENBNB]: 'venbnb',
    [Pair.YOYOBNB]: 'yoyobnb',
    [Pair.POWRBNB]: 'powrbnb',
    [Pair.VENBTC]: 'venbtc',
    [Pair.VENETH]: 'veneth',
    [Pair.KMDBTC]: 'kmdbtc',
    [Pair.KMDETH]: 'kmdeth',
    [Pair.NULSBNB]: 'nulsbnb',
    [Pair.RCNBTC]: 'rcnbtc',
    [Pair.RCNETH]: 'rcneth',
    [Pair.RCNBNB]: 'rcnbnb',
    [Pair.NULSBTC]: 'nulsbtc',
    [Pair.NULSETH]: 'nulseth',
    [Pair.RDNBTC]: 'rdnbtc',
    [Pair.RDNETH]: 'rdneth',
    [Pair.RDNBNB]: 'rdnbnb',
    [Pair.XMRBTC]: 'xmrbtc',
    [Pair.XMRETH]: 'xmreth',
    [Pair.DLTBNB]: 'dltbnb',
    [Pair.WTCBNB]: 'wtcbnb',
    [Pair.DLTBTC]: 'dltbtc',
    [Pair.DLTETH]: 'dlteth',
    [Pair.AMBBTC]: 'ambbtc',
    [Pair.AMBETH]: 'ambeth',
    [Pair.AMBBNB]: 'ambbnb',
    [Pair.BCCETH]: 'bcceth',
    [Pair.BCCUSDT]: 'bccusdt',
    [Pair.BCCBNB]: 'bccbnb',
    [Pair.BATBTC]: 'batbtc',
    [Pair.BATETH]: 'bateth',
    [Pair.BATBNB]: 'batbnb',
    [Pair.BCPTBTC]: 'bcptbtc',
    [Pair.BCPTETH]: 'bcpteth',
    [Pair.BCPTBNB]: 'bcptbnb',
    [Pair.ARNBTC]: 'arnbtc',
    [Pair.ARNETH]: 'arneth',
    [Pair.GVTBTC]: 'gvtbtc',
    [Pair.GVTETH]: 'gvteth',
    [Pair.CDTBTC]: 'cdtbtc',
    [Pair.CDTETH]: 'cdteth',
    [Pair.GXSBTC]: 'gxsbtc',
    [Pair.GXSETH]: 'gxseth',
    [Pair.NEOUSDT]: 'neousdt',
    [Pair.NEOBNB]: 'neobnb',
    [Pair.POEBTC]: 'poebtc',
    [Pair.POEETH]: 'poeeth',
    [Pair.QSPBTC]: 'qspbtc',
    [Pair.QSPETH]: 'qspeth',
    [Pair.QSPBNB]: 'qspbnb',
    [Pair.BTSBTC]: 'btsbtc',
    [Pair.BTSETH]: 'btseth',
    [Pair.BTSBNB]: 'btsbnb',
    [Pair.XZCBTC]: 'xzcbtc',
    [Pair.XZCETH]: 'xzceth',
    [Pair.XZCBNB]: 'xzcbnb',
    [Pair.LSKBTC]: 'lskbtc',
    [Pair.LSKETH]: 'lsketh',
    [Pair.LSKBNB]: 'lskbnb',
    [Pair.TNTBTC]: 'tntbtc',
    [Pair.TNTETH]: 'tnteth',
    [Pair.FUELBTC]: 'fuelbtc',
    [Pair.FUELETH]: 'fueleth',
    [Pair.MANABTC]: 'manabtc',
    [Pair.MANAETH]: 'manaeth',
    [Pair.BCDBTC]: 'bcdbtc',
    [Pair.BCDETH]: 'bcdeth',
    [Pair.DGDBTC]: 'dgdbtc',
    [Pair.DGDETH]: 'dgdeth',
    [Pair.IOTABNB]: 'iotabnb',
    [Pair.ADXBTC]: 'adxbtc',
    [Pair.ADXETH]: 'adxeth',
    [Pair.ADXBNB]: 'adxbnb',
    [Pair.ADABTC]: 'adabtc',
    [Pair.ADAETH]: 'adaeth',
    [Pair.PPTBTC]: 'pptbtc',
    [Pair.PPTETH]: 'ppteth',
    [Pair.CMTBTC]: 'cmtbtc',
    [Pair.CMTETH]: 'cmteth',
    [Pair.CMTBNB]: 'cmtbnb',
    [Pair.XLMBTC]: 'xlmbtc',
    [Pair.XLMETH]: 'xlmeth',
    [Pair.XLMBNB]: 'xlmbnb',
    [Pair.CNDBTC]: 'cndbtc',
    [Pair.CNDETH]: 'cndeth',
    [Pair.CNDBNB]: 'cndbnb',
    [Pair.LENDBTC]: 'lendbtc',
    [Pair.LENDETH]: 'lendeth',
    [Pair.WABIBTC]: 'wabibtc',
    [Pair.WABIETH]: 'wabieth',
    [Pair.WABIBNB]: 'wabibnb',
    [Pair.LTCETH]: 'ltceth',
    [Pair.LTCUSDT]: 'ltcusdt',
    [Pair.LTCBNB]: 'ltcbnb',
    [Pair.TNBBTC]: 'tnbbtc',
    [Pair.TNBETH]: 'tnbeth',
    [Pair.WAVESBTC]: 'wavesbtc',
    [Pair.WAVESETH]: 'waveseth',
    [Pair.WAVESBNB]: 'wavesbnb',
    [Pair.GTOBTC]: 'gtobtc',
    [Pair.GTOETH]: 'gtoeth',
    [Pair.GTOBNB]: 'gtobnb',
    [Pair.ICXBTC]: 'icxbtc',
    [Pair.ICXETH]: 'icxeth',
    [Pair.ICXBNB]: 'icxbnb',
    [Pair.OSTBTC]: 'ostbtc',
    [Pair.OSTETH]: 'osteth',
    [Pair.OSTBNB]: 'ostbnb',
    [Pair.ELFBTC]: 'elfbtc',
    [Pair.ELFETH]: 'elfeth',
    [Pair.AIONBTC]: 'aionbtc',
    [Pair.AIONETH]: 'aioneth',
    [Pair.AIONBNB]: 'aionbnb',
    [Pair.NEBLBTC]: 'neblbtc',
    [Pair.NEBLETH]: 'nebleth',
    [Pair.NEBLBNB]: 'neblbnb',
    [Pair.BRDBTC]: 'brdbtc',
    [Pair.BRDETH]: 'brdeth',
    [Pair.BRDBNB]: 'brdbnb',
    [Pair.MCOBNB]: 'mcobnb',
    [Pair.EDOBTC]: 'edobtc',
    [Pair.EDOETH]: 'edoeth',
    [Pair.WINGSBTC]: 'wingsbtc',
    [Pair.WINGSETH]: 'wingseth',
    [Pair.NAVBTC]: 'navbtc',
    [Pair.NAVETH]: 'naveth',
    [Pair.NAVBNB]: 'navbnb',
    [Pair.LUNBTC]: 'lunbtc',
    [Pair.LUNETH]: 'luneth',
    [Pair.TRIGBTC]: 'trigbtc',
    [Pair.TRIGETH]: 'trigeth',
    [Pair.TRIGBNB]: 'trigbnb',
    [Pair.APPCBTC]: 'appcbtc',
    [Pair.APPCETH]: 'appceth',
    [Pair.APPCBNB]: 'appcbnb',
    [Pair.VIBEBTC]: 'vibebtc',
    [Pair.VIBEETH]: 'vibeeth',
    [Pair.RLCBTC]: 'rlcbtc',
    [Pair.RLCETH]: 'rlceth',
    [Pair.RLCBNB]: 'rlcbnb',
    [Pair.INSBTC]: 'insbtc',
    [Pair.INSETH]: 'inseth',
    [Pair.PIVXBTC]: 'pivxbtc',
    [Pair.PIVXETH]: 'pivxeth',
    [Pair.PIVXBNB]: 'pivxbnb',
    [Pair.IOSTBTC]: 'iostbtc',
    [Pair.IOSTETH]: 'iosteth',
    [Pair.CHATBTC]: 'chatbtc',
    [Pair.CHATETH]: 'chateth',
    [Pair.STEEMBTC]: 'steembtc',
    [Pair.STEEMETH]: 'steemeth',
    [Pair.STEEMBNB]: 'steembnb',
    [Pair.NANOBTC]: 'nanobtc',
    [Pair.NANOETH]: 'nanoeth',
    [Pair.NANOBNB]: 'nanobnb',
    [Pair.VIABTC]: 'viabtc',
    [Pair.VIAETH]: 'viaeth',
    [Pair.VIABNB]: 'viabnb',
    [Pair.BLZBTC]: 'blzbtc',
    [Pair.BLZETH]: 'blzeth',
    [Pair.BLZBNB]: 'blzbnb',
    [Pair.AEBTC]: 'aebtc',
    [Pair.AEETH]: 'aeeth',
    [Pair.AEBNB]: 'aebnb',
    [Pair.RPXBTC]: 'rpxbtc',
    [Pair.RPXETH]: 'rpxeth',
    [Pair.RPXBNB]: 'rpxbnb',
    [Pair.NCASHBTC]: 'ncashbtc',
    [Pair.NCASHETH]: 'ncasheth',
    [Pair.NCASHBNB]: 'ncashbnb',
    [Pair.POABTC]: 'poabtc',
    [Pair.POAETH]: 'poaeth',
    [Pair.POABNB]: 'poabnb',
    [Pair.ZILBTC]: 'zilbtc',
    [Pair.ZILETH]: 'zileth',
    [Pair.ZILBNB]: 'zilbnb',
    [Pair.ONTBTC]: 'ontbtc',
    [Pair.ONTETH]: 'onteth',
    [Pair.ONTBNB]: 'ontbnb',
    [Pair.STORMBTC]: 'stormbtc',
    [Pair.STORMETH]: 'stormeth',
    [Pair.STORMBNB]: 'stormbnb',
    [Pair.QTUMBNB]: 'qtumbnb',
    [Pair.QTUMUSDT]: 'qtumusdt',
    [Pair.XEMBTC]: 'xembtc',
    [Pair.XEMETH]: 'xemeth',
    [Pair.XEMBNB]: 'xembnb',
    [Pair.WANBTC]: 'wanbtc',
    [Pair.WANETH]: 'waneth',
    [Pair.WANBNB]: 'wanbnb',
    [Pair.WPRBTC]: 'wprbtc',
    [Pair.WPRETH]: 'wpreth',
    [Pair.QLCBTC]: 'qlcbtc',
    [Pair.QLCETH]: 'qlceth',
    [Pair.SYSBTC]: 'sysbtc',
    [Pair.SYSETH]: 'syseth',
    [Pair.SYSBNB]: 'sysbnb',
    [Pair.QLCBNB]: 'qlcbnb',
    [Pair.GRSBTC]: 'grsbtc',
    [Pair.GRSETH]: 'grseth',
    [Pair.ADAUSDT]: 'adausdt',
    [Pair.ADABNB]: 'adabnb',
    [Pair.CLOAKBTC]: 'cloakbtc',
    [Pair.CLOAKETH]: 'cloaketh',
    [Pair.GNTBTC]: 'gntbtc',
    [Pair.GNTETH]: 'gnteth',
    [Pair.GNTBNB]: 'gntbnb',
    [Pair.LOOMBTC]: 'loombtc',
    [Pair.LOOMETH]: 'loometh',
    [Pair.LOOMBNB]: 'loombnb',
    [Pair.XRPUSDT]: 'xrpusdt',
    [Pair.BCNBTC]: 'bcnbtc',
    [Pair.BCNETH]: 'bcneth',
    [Pair.BCNBNB]: 'bcnbnb',
    [Pair.REPBTC]: 'repbtc',
    [Pair.REPETH]: 'repeth',
    [Pair.REPBNB]: 'repbnb',
    [Pair.BTCTUSD]: 'btctusd',
    [Pair.TUSDBTC]: 'tusdbtc',
    [Pair.ETHTUSD]: 'ethtusd',
    [Pair.TUSDETH]: 'tusdeth',
    [Pair.TUSDBNB]: 'tusdbnb',
    [Pair.ZENBTC]: 'zenbtc',
    [Pair.ZENETH]: 'zeneth',
    [Pair.ZENBNB]: 'zenbnb',
    [Pair.SKYBTC]: 'skybtc',
    [Pair.SKYETH]: 'skyeth',
    [Pair.SKYBNB]: 'skybnb',
    [Pair.EOSUSDT]: 'eosusdt',
    [Pair.EOSBNB]: 'eosbnb',
    [Pair.CVCBTC]: 'cvcbtc',
    [Pair.CVCETH]: 'cvceth',
    [Pair.CVCBNB]: 'cvcbnb',
    [Pair.THETABTC]: 'thetabtc',
    [Pair.THETAETH]: 'thetaeth',
    [Pair.THETABNB]: 'thetabnb',
    [Pair.XRPBNB]: 'xrpbnb',
    [Pair.TUSDUSDT]: 'tusdusdt',
    [Pair.IOTAUSDT]: 'iotausdt',
    [Pair.XLMUSDT]: 'xlmusdt',
    [Pair.IOTXBTC]: 'iotxbtc',
    [Pair.IOTXETH]: 'iotxeth',
    [Pair.QKCBTC]: 'qkcbtc',
    [Pair.QKCETH]: 'qkceth',
    [Pair.AGIBTC]: 'agibtc',
    [Pair.AGIETH]: 'agieth',
    [Pair.AGIBNB]: 'agibnb',
    [Pair.NXSBTC]: 'nxsbtc',
    [Pair.NXSETH]: 'nxseth',
    [Pair.NXSBNB]: 'nxsbnb',
    [Pair.ENJBNB]: 'enjbnb',
    [Pair.DATABTC]: 'databtc',
    [Pair.DATAETH]: 'dataeth',
    [Pair.ONTUSDT]: 'ontusdt',
    [Pair.TRXBNB]: 'trxbnb',
    [Pair.TRXUSDT]: 'trxusdt',
    [Pair.ETCUSDT]: 'etcusdt',
    [Pair.ETCBNB]: 'etcbnb',
    [Pair.ICXUSDT]: 'icxusdt',
    [Pair.SCBTC]: 'scbtc',
    [Pair.SCETH]: 'sceth',
    [Pair.SCBNB]: 'scbnb',
    [Pair.NPXSBTC]: 'npxsbtc',
    [Pair.NPXSETH]: 'npxseth',
    [Pair.VENUSDT]: 'venusdt',
    [Pair.KEYBTC]: 'keybtc',
    [Pair.KEYETH]: 'keyeth',
    [Pair.NASBTC]: 'nasbtc',
    [Pair.NASETH]: 'naseth',
    [Pair.NASBNB]: 'nasbnb',
    [Pair.MFTBTC]: 'mftbtc',
    [Pair.MFTETH]: 'mfteth',
    [Pair.MFTBNB]: 'mftbnb',
    [Pair.DENTBTC]: 'dentbtc',
    [Pair.DENTETH]: 'denteth',
    [Pair.ARDRBTC]: 'ardrbtc',
    [Pair.ARDRETH]: 'ardreth',
    [Pair.ARDRBNB]: 'ardrbnb',
    [Pair.NULSUSDT]: 'nulsusdt',
    [Pair.HOTBTC]: 'hotbtc',
    [Pair.HOTETH]: 'hoteth',
    [Pair.VETBTC]: 'vetbtc',
    [Pair.VETETH]: 'veteth',
    [Pair.VETUSDT]: 'vetusdt',
    [Pair.VETBNB]: 'vetbnb',
    [Pair.DOCKBTC]: 'dockbtc',
    [Pair.DOCKETH]: 'docketh',
    [Pair.POLYBTC]: 'polybtc',
    [Pair.POLYBNB]: 'polybnb',
    [Pair.PHXBTC]: 'phxbtc',
    [Pair.PHXETH]: 'phxeth',
    [Pair.PHXBNB]: 'phxbnb',
    [Pair.HCBTC]: 'hcbtc',
    [Pair.HCETH]: 'hceth',
    [Pair.GOBTC]: 'gobtc',
    [Pair.GOBNB]: 'gobnb',
    [Pair.PAXBTC]: 'paxbtc',
    [Pair.PAXBNB]: 'paxbnb',
    [Pair.PAXUSDT]: 'paxusdt',
    [Pair.PAXETH]: 'paxeth',
    [Pair.RVNBTC]: 'rvnbtc',
    [Pair.RVNBNB]: 'rvnbnb',
    [Pair.DCRBTC]: 'dcrbtc',
    [Pair.DCRBNB]: 'dcrbnb',
    [Pair.USDCBNB]: 'usdcbnb',
    [Pair.MITHBTC]: 'mithbtc',
    [Pair.MITHBNB]: 'mithbnb',
    [Pair.BCHABCBTC]: 'bchabcbtc',
    [Pair.BCHSVBTC]: 'bchsvbtc',
    [Pair.BCHABCUSDT]: 'bchabcusdt',
    [Pair.BCHSVUSDT]: 'bchsvusdt',
    [Pair.BNBPAX]: 'bnbpax',
    [Pair.BTCPAX]: 'btcpax',
    [Pair.ETHPAX]: 'ethpax',
    [Pair.XRPPAX]: 'xrppax',
    [Pair.EOSPAX]: 'eospax',
    [Pair.XLMPAX]: 'xlmpax',
    [Pair.RENBTC]: 'renbtc',
    [Pair.RENBNB]: 'renbnb',
    [Pair.BNBTUSD]: 'bnbtusd',
    [Pair.XRPTUSD]: 'xrptusd',
    [Pair.EOSTUSD]: 'eostusd',
    [Pair.XLMTUSD]: 'xlmtusd',
    [Pair.BNBUSDC]: 'bnbusdc',
    [Pair.BTCUSDC]: 'btcusdc',
    [Pair.ETHUSDC]: 'ethusdc',
    [Pair.XRPUSDC]: 'xrpusdc',
    [Pair.EOSUSDC]: 'eosusdc',
    [Pair.XLMUSDC]: 'xlmusdc',
    [Pair.USDCUSDT]: 'usdcusdt',
    [Pair.ADATUSD]: 'adatusd',
    [Pair.TRXTUSD]: 'trxtusd',
    [Pair.NEOTUSD]: 'neotusd',
    [Pair.TRXXRP]: 'trxxrp',
    [Pair.XZCXRP]: 'xzcxrp',
    [Pair.PAXTUSD]: 'paxtusd',
    [Pair.USDCTUSD]: 'usdctusd',
    [Pair.USDCPAX]: 'usdcpax',
    [Pair.LINKUSDT]: 'linkusdt',
    [Pair.LINKTUSD]: 'linktusd',
    [Pair.LINKPAX]: 'linkpax',
    [Pair.LINKUSDC]: 'linkusdc',
    [Pair.WAVESUSDT]: 'wavesusdt',
    [Pair.WAVESTUSD]: 'wavestusd',
    [Pair.WAVESPAX]: 'wavespax',
    [Pair.WAVESUSDC]: 'wavesusdc',
    [Pair.BCHABCTUSD]: 'bchabctusd',
    [Pair.BCHABCPAX]: 'bchabcpax',
    [Pair.BCHABCUSDC]: 'bchabcusdc',
    [Pair.BCHSVTUSD]: 'bchsvtusd',
    [Pair.BCHSVPAX]: 'bchsvpax',
    [Pair.BCHSVUSDC]: 'bchsvusdc',
    [Pair.LTCTUSD]: 'ltctusd',
    [Pair.LTCPAX]: 'ltcpax',
    [Pair.LTCUSDC]: 'ltcusdc',
    [Pair.TRXPAX]: 'trxpax',
    [Pair.TRXUSDC]: 'trxusdc',
    [Pair.BTTBTC]: 'bttbtc',
    [Pair.BTTBNB]: 'bttbnb',
    [Pair.BTTUSDT]: 'bttusdt',
    [Pair.BNBUSDS]: 'bnbusds',
    [Pair.BTCUSDS]: 'btcusds',
    [Pair.USDSUSDT]: 'usdsusdt',
    [Pair.USDSPAX]: 'usdspax',
    [Pair.USDSTUSD]: 'usdstusd',
    [Pair.USDSUSDC]: 'usdsusdc',
    [Pair.BTTPAX]: 'bttpax',
    [Pair.BTTTUSD]: 'btttusd',
    [Pair.BTTUSDC]: 'bttusdc',
    [Pair.ONGBNB]: 'ongbnb',
    [Pair.ONGBTC]: 'ongbtc',
    [Pair.ONGUSDT]: 'ongusdt',
    [Pair.HOTBNB]: 'hotbnb',
    [Pair.HOTUSDT]: 'hotusdt',
    [Pair.ZILUSDT]: 'zilusdt',
    [Pair.ZRXBNB]: 'zrxbnb',
    [Pair.ZRXUSDT]: 'zrxusdt',
    [Pair.FETBNB]: 'fetbnb',
    [Pair.FETBTC]: 'fetbtc',
    [Pair.FETUSDT]: 'fetusdt',
    [Pair.BATUSDT]: 'batusdt',
    [Pair.XMRBNB]: 'xmrbnb',
    [Pair.XMRUSDT]: 'xmrusdt',
    [Pair.ZECBNB]: 'zecbnb',
    [Pair.ZECUSDT]: 'zecusdt',
    [Pair.ZECPAX]: 'zecpax',
    [Pair.ZECTUSD]: 'zectusd',
    [Pair.ZECUSDC]: 'zecusdc',
    [Pair.IOSTBNB]: 'iostbnb',
    [Pair.IOSTUSDT]: 'iostusdt',
    [Pair.CELRBNB]: 'celrbnb',
    [Pair.CELRBTC]: 'celrbtc',
    [Pair.CELRUSDT]: 'celrusdt',
    [Pair.ADAPAX]: 'adapax',
    [Pair.ADAUSDC]: 'adausdc',
    [Pair.NEOPAX]: 'neopax',
    [Pair.NEOUSDC]: 'neousdc',
    [Pair.DASHBNB]: 'dashbnb',
    [Pair.DASHUSDT]: 'dashusdt',
    [Pair.NANOUSDT]: 'nanousdt',
    [Pair.OMGBNB]: 'omgbnb',
    [Pair.OMGUSDT]: 'omgusdt',
    [Pair.THETAUSDT]: 'thetausdt',
    [Pair.ENJUSDT]: 'enjusdt',
    [Pair.MITHUSDT]: 'mithusdt',
    [Pair.MATICBNB]: 'maticbnb',
    [Pair.MATICBTC]: 'maticbtc',
    [Pair.MATICUSDT]: 'maticusdt',
    [Pair.ATOMBNB]: 'atombnb',
    [Pair.ATOMBTC]: 'atombtc',
    [Pair.ATOMUSDT]: 'atomusdt',
    [Pair.ATOMUSDC]: 'atomusdc',
    [Pair.ATOMPAX]: 'atompax',
    [Pair.ATOMTUSD]: 'atomtusd',
    [Pair.ETCUSDC]: 'etcusdc',
    [Pair.ETCPAX]: 'etcpax',
    [Pair.ETCTUSD]: 'etctusd',
    [Pair.BATUSDC]: 'batusdc',
    [Pair.BATPAX]: 'batpax',
    [Pair.BATTUSD]: 'battusd',
    [Pair.PHBBNB]: 'phbbnb',
    [Pair.PHBBTC]: 'phbbtc',
    [Pair.PHBUSDC]: 'phbusdc',
    [Pair.PHBTUSD]: 'phbtusd',
    [Pair.PHBPAX]: 'phbpax',
    [Pair.TFUELBNB]: 'tfuelbnb',
    [Pair.TFUELBTC]: 'tfuelbtc',
    [Pair.TFUELUSDT]: 'tfuelusdt',
    [Pair.TFUELUSDC]: 'tfuelusdc',
    [Pair.TFUELTUSD]: 'tfueltusd',
    [Pair.TFUELPAX]: 'tfuelpax',
    [Pair.ONEBNB]: 'onebnb',
    [Pair.ONEBTC]: 'onebtc',
    [Pair.ONEUSDT]: 'oneusdt',
    [Pair.ONETUSD]: 'onetusd',
    [Pair.ONEPAX]: 'onepax',
    [Pair.ONEUSDC]: 'oneusdc',
    [Pair.FTMBNB]: 'ftmbnb',
    [Pair.FTMBTC]: 'ftmbtc',
    [Pair.FTMUSDT]: 'ftmusdt',
    [Pair.FTMTUSD]: 'ftmtusd',
    [Pair.FTMPAX]: 'ftmpax',
    [Pair.FTMUSDC]: 'ftmusdc',
    [Pair.BTCBBTC]: 'btcbbtc',
    [Pair.BCPTTUSD]: 'bcpttusd',
    [Pair.BCPTPAX]: 'bcptpax',
    [Pair.BCPTUSDC]: 'bcptusdc',
    [Pair.ALGOBNB]: 'algobnb',
    [Pair.ALGOBTC]: 'algobtc',
    [Pair.ALGOUSDT]: 'algousdt',
    [Pair.ALGOTUSD]: 'algotusd',
    [Pair.ALGOPAX]: 'algopax',
    [Pair.ALGOUSDC]: 'algousdc',
    [Pair.USDSBUSDT]: 'usdsbusdt',
    [Pair.USDSBUSDS]: 'usdsbusds',
    [Pair.GTOUSDT]: 'gtousdt',
    [Pair.GTOPAX]: 'gtopax',
    [Pair.GTOTUSD]: 'gtotusd',
    [Pair.GTOUSDC]: 'gtousdc',
    [Pair.ERDBNB]: 'erdbnb',
    [Pair.ERDBTC]: 'erdbtc',
    [Pair.ERDUSDT]: 'erdusdt',
    [Pair.ERDPAX]: 'erdpax',
    [Pair.ERDUSDC]: 'erdusdc',
    [Pair.DOGEBNB]: 'dogebnb',
    [Pair.DOGEBTC]: 'dogebtc',
    [Pair.DOGEUSDT]: 'dogeusdt',
    [Pair.DOGEPAX]: 'dogepax',
    [Pair.DOGEUSDC]: 'dogeusdc',
    [Pair.DUSKBNB]: 'duskbnb',
    [Pair.DUSKBTC]: 'duskbtc',
    [Pair.DUSKUSDT]: 'duskusdt',
    [Pair.DUSKUSDC]: 'duskusdc',
    [Pair.DUSKPAX]: 'duskpax',
    [Pair.BGBPUSDC]: 'bgbpusdc',
    [Pair.ANKRBNB]: 'ankrbnb',
    [Pair.ANKRBTC]: 'ankrbtc',
    [Pair.ANKRUSDT]: 'ankrusdt',
    [Pair.ANKRTUSD]: 'ankrtusd',
    [Pair.ANKRPAX]: 'ankrpax',
    [Pair.ANKRUSDC]: 'ankrusdc',
    [Pair.ONTPAX]: 'ontpax',
    [Pair.ONTUSDC]: 'ontusdc',
    [Pair.WINBNB]: 'winbnb',
    [Pair.WINBTC]: 'winbtc',
    [Pair.WINUSDT]: 'winusdt',
    [Pair.WINUSDC]: 'winusdc',
    [Pair.COSBNB]: 'cosbnb',
    [Pair.COSBTC]: 'cosbtc',
    [Pair.COSUSDT]: 'cosusdt',
    [Pair.TUSDBTUSD]: 'tusdbtusd',
    [Pair.NPXSUSDT]: 'npxsusdt',
    [Pair.NPXSUSDC]: 'npxsusdc',
    [Pair.COCOSBNB]: 'cocosbnb',
    [Pair.COCOSBTC]: 'cocosbtc',
    [Pair.COCOSUSDT]: 'cocosusdt',
    [Pair.MTLUSDT]: 'mtlusdt',
    [Pair.TOMOBNB]: 'tomobnb',
    [Pair.TOMOBTC]: 'tomobtc',
    [Pair.TOMOUSDT]: 'tomousdt',
    [Pair.TOMOUSDC]: 'tomousdc',
    [Pair.PERLBNB]: 'perlbnb',
    [Pair.PERLBTC]: 'perlbtc',
    [Pair.PERLUSDC]: 'perlusdc',
    [Pair.PERLUSDT]: 'perlusdt',
    [Pair.DENTUSDT]: 'dentusdt',
    [Pair.MFTUSDT]: 'mftusdt',
    [Pair.KEYUSDT]: 'keyusdt',
    [Pair.STORMUSDT]: 'stormusdt',
    [Pair.DOCKUSDT]: 'dockusdt',
    [Pair.WANUSDT]: 'wanusdt',
    [Pair.FUNUSDT]: 'funusdt',
    [Pair.CVCUSDT]: 'cvcusdt',
    [Pair.BTTTRX]: 'btttrx',
    [Pair.WINTRX]: 'wintrx',
    [Pair.CHZBNB]: 'chzbnb',
    [Pair.CHZBTC]: 'chzbtc',
    [Pair.CHZUSDT]: 'chzusdt',
    [Pair.BANDBNB]: 'bandbnb',
    [Pair.BANDBTC]: 'bandbtc',
    [Pair.BANDUSDT]: 'bandusdt',
    [Pair.BNBBUSD]: 'bnbbusd',
    [Pair.BTCBUSD]: 'btcbusd',
    [Pair.BUSDUSDT]: 'busdusdt',
    [Pair.BEAMBNB]: 'beambnb',
    [Pair.BEAMBTC]: 'beambtc',
    [Pair.BEAMUSDT]: 'beamusdt',
    [Pair.XTZBNB]: 'xtzbnb',
    [Pair.XTZBTC]: 'xtzbtc',
    [Pair.XTZUSDT]: 'xtzusdt',
    [Pair.RENUSDT]: 'renusdt',
    [Pair.RVNUSDT]: 'rvnusdt',
    [Pair.HCUSDT]: 'hcusdt',
    [Pair.HBARBNB]: 'hbarbnb',
    [Pair.HBARBTC]: 'hbarbtc',
    [Pair.HBARUSDT]: 'hbarusdt',
    [Pair.NKNBNB]: 'nknbnb',
    [Pair.NKNBTC]: 'nknbtc',
    [Pair.NKNUSDT]: 'nknusdt',
    [Pair.XRPBUSD]: 'xrpbusd',
    [Pair.ETHBUSD]: 'ethbusd',
    [Pair.BCHABCBUSD]: 'bchabcbusd',
    [Pair.LTCBUSD]: 'ltcbusd',
    [Pair.LINKBUSD]: 'linkbusd',
    [Pair.ETCBUSD]: 'etcbusd',
    [Pair.STXBNB]: 'stxbnb',
    [Pair.STXBTC]: 'stxbtc',
    [Pair.STXUSDT]: 'stxusdt',
    [Pair.KAVABNB]: 'kavabnb',
    [Pair.KAVABTC]: 'kavabtc',
    [Pair.KAVAUSDT]: 'kavausdt',
    [Pair.BUSDNGN]: 'busdngn',
    [Pair.BNBNGN]: 'bnbngn',
    [Pair.BTCNGN]: 'btcngn',
    [Pair.ARPABNB]: 'arpabnb',
    [Pair.ARPABTC]: 'arpabtc',
    [Pair.ARPAUSDT]: 'arpausdt',
    [Pair.TRXBUSD]: 'trxbusd',
    [Pair.EOSBUSD]: 'eosbusd',
    [Pair.IOTXUSDT]: 'iotxusdt',
    [Pair.RLCUSDT]: 'rlcusdt',
    [Pair.MCOUSDT]: 'mcousdt',
    [Pair.XLMBUSD]: 'xlmbusd',
    [Pair.ADABUSD]: 'adabusd',
    [Pair.CTXCBNB]: 'ctxcbnb',
    [Pair.CTXCBTC]: 'ctxcbtc',
    [Pair.CTXCUSDT]: 'ctxcusdt',
    [Pair.BCHBNB]: 'bchbnb',
    [Pair.BCHBTC]: 'bchbtc',
    [Pair.BCHUSDT]: 'bchusdt',
    [Pair.BCHUSDC]: 'bchusdc',
    [Pair.BCHTUSD]: 'bchtusd',
    [Pair.BCHPAX]: 'bchpax',
    [Pair.BCHBUSD]: 'bchbusd',
    [Pair.BTCRUB]: 'btcrub',
    [Pair.ETHRUB]: 'ethrub',
    [Pair.XRPRUB]: 'xrprub',
    [Pair.BNBRUB]: 'bnbrub',
    [Pair.TROYBNB]: 'troybnb',
    [Pair.TROYBTC]: 'troybtc',
    [Pair.TROYUSDT]: 'troyusdt',
    [Pair.BUSDRUB]: 'busdrub',
    [Pair.QTUMBUSD]: 'qtumbusd',
    [Pair.VETBUSD]: 'vetbusd',
    [Pair.VITEBNB]: 'vitebnb',
    [Pair.VITEBTC]: 'vitebtc',
    [Pair.VITEUSDT]: 'viteusdt',
    [Pair.FTTBNB]: 'fttbnb',
    [Pair.FTTBTC]: 'fttbtc',
    [Pair.FTTUSDT]: 'fttusdt',
    [Pair.BTCTRY]: 'btctry',
    [Pair.BNBTRY]: 'bnbtry',
    [Pair.BUSDTRY]: 'busdtry',
    [Pair.ETHTRY]: 'ethtry',
    [Pair.XRPTRY]: 'xrptry',
    [Pair.USDTTRY]: 'usdttry',
    [Pair.USDTRUB]: 'usdtrub',
    [Pair.BTCEUR]: 'btceur',
    [Pair.ETHEUR]: 'etheur',
    [Pair.BNBEUR]: 'bnbeur',
    [Pair.XRPEUR]: 'xrpeur',
    [Pair.EURBUSD]: 'eurbusd',
    [Pair.EURUSDT]: 'eurusdt',
    [Pair.OGNBNB]: 'ognbnb',
    [Pair.OGNBTC]: 'ognbtc',
    [Pair.OGNUSDT]: 'ognusdt',
    [Pair.DREPBNB]: 'drepbnb',
    [Pair.DREPBTC]: 'drepbtc',
    [Pair.DREPUSDT]: 'drepusdt',
    [Pair.BULLUSDT]: 'bullusdt',
    [Pair.BULLBUSD]: 'bullbusd',
    [Pair.BEARUSDT]: 'bearusdt',
    [Pair.BEARBUSD]: 'bearbusd',
    [Pair.ETHBULLUSDT]: 'ethbullusdt',
    [Pair.ETHBULLBUSD]: 'ethbullbusd',
    [Pair.ETHBEARUSDT]: 'ethbearusdt',
    [Pair.ETHBEARBUSD]: 'ethbearbusd',
    [Pair.TCTBNB]: 'tctbnb',
    [Pair.TCTBTC]: 'tctbtc',
    [Pair.TCTUSDT]: 'tctusdt',
    [Pair.WRXBNB]: 'wrxbnb',
    [Pair.WRXBTC]: 'wrxbtc',
    [Pair.WRXUSDT]: 'wrxusdt',
    [Pair.ICXBUSD]: 'icxbusd',
    [Pair.BTSUSDT]: 'btsusdt',
    [Pair.BTSBUSD]: 'btsbusd',
    [Pair.LSKUSDT]: 'lskusdt',
    [Pair.BNTUSDT]: 'bntusdt',
    [Pair.BNTBUSD]: 'bntbusd',
    [Pair.LTOBNB]: 'ltobnb',
    [Pair.LTOBTC]: 'ltobtc',
    [Pair.LTOUSDT]: 'ltousdt',
    [Pair.ATOMBUSD]: 'atombusd',
    [Pair.DASHBUSD]: 'dashbusd',
    [Pair.NEOBUSD]: 'neobusd',
    [Pair.WAVESBUSD]: 'wavesbusd',
    [Pair.XTZBUSD]: 'xtzbusd',
    [Pair.EOSBULLUSDT]: 'eosbullusdt',
    [Pair.EOSBULLBUSD]: 'eosbullbusd',
    [Pair.EOSBEARUSDT]: 'eosbearusdt',
    [Pair.EOSBEARBUSD]: 'eosbearbusd',
    [Pair.XRPBULLUSDT]: 'xrpbullusdt',
    [Pair.XRPBULLBUSD]: 'xrpbullbusd',
    [Pair.XRPBEARUSDT]: 'xrpbearusdt',
    [Pair.XRPBEARBUSD]: 'xrpbearbusd',
    [Pair.BATBUSD]: 'batbusd',
    [Pair.ENJBUSD]: 'enjbusd',
    [Pair.NANOBUSD]: 'nanobusd',
    [Pair.ONTBUSD]: 'ontbusd',
    [Pair.RVNBUSD]: 'rvnbusd',
    [Pair.STRATBUSD]: 'stratbusd',
    [Pair.STRATBNB]: 'stratbnb',
    [Pair.STRATUSDT]: 'stratusdt',
    [Pair.AIONBUSD]: 'aionbusd',
    [Pair.AIONUSDT]: 'aionusdt',
    [Pair.MBLBNB]: 'mblbnb',
    [Pair.MBLBTC]: 'mblbtc',
    [Pair.MBLUSDT]: 'mblusdt',
    [Pair.COTIBNB]: 'cotibnb',
    [Pair.COTIBTC]: 'cotibtc',
    [Pair.COTIUSDT]: 'cotiusdt',
    [Pair.ALGOBUSD]: 'algobusd',
    [Pair.BTTBUSD]: 'bttbusd',
    [Pair.TOMOBUSD]: 'tomobusd',
    [Pair.XMRBUSD]: 'xmrbusd',
    [Pair.ZECBUSD]: 'zecbusd',
    [Pair.BNBBULLUSDT]: 'bnbbullusdt',
    [Pair.BNBBULLBUSD]: 'bnbbullbusd',
    [Pair.BNBBEARUSDT]: 'bnbbearusdt',
    [Pair.BNBBEARBUSD]: 'bnbbearbusd',
    [Pair.STPTBNB]: 'stptbnb',
    [Pair.STPTBTC]: 'stptbtc',
    [Pair.STPTUSDT]: 'stptusdt',
    [Pair.BTCZAR]: 'btczar',
    [Pair.ETHZAR]: 'ethzar',
    [Pair.BNBZAR]: 'bnbzar',
    [Pair.USDTZAR]: 'usdtzar',
    [Pair.BUSDZAR]: 'busdzar',
    [Pair.BTCBKRW]: 'btcbkrw',
    [Pair.ETHBKRW]: 'ethbkrw',
    [Pair.BNBBKRW]: 'bnbbkrw',
    [Pair.WTCUSDT]: 'wtcusdt',
    [Pair.DATABUSD]: 'databusd',
    [Pair.DATAUSDT]: 'datausdt',
    [Pair.XZCUSDT]: 'xzcusdt',
    [Pair.SOLBNB]: 'solbnb',
    [Pair.SOLBTC]: 'solbtc',
    [Pair.SOLBUSD]: 'solbusd',
    [Pair.BTCIDRT]: 'btcidrt',
    [Pair.BNBIDRT]: 'bnbidrt',
    [Pair.USDTIDRT]: 'usdtidrt',
    [Pair.BUSDIDRT]: 'busdidrt',
    [Pair.CTSIBTC]: 'ctsibtc',
    [Pair.CTSIUSDT]: 'ctsiusdt',
    [Pair.CTSIBNB]: 'ctsibnb',
    [Pair.CTSIBUSD]: 'ctsibusd',
    [Pair.HIVEBNB]: 'hivebnb',
    [Pair.HIVEBTC]: 'hivebtc',
    [Pair.HIVEUSDT]: 'hiveusdt',
    [Pair.CHRBNB]: 'chrbnb',
    [Pair.CHRBTC]: 'chrbtc',
    [Pair.CHRUSDT]: 'chrusdt',
    [Pair.BTCUPUSDT]: 'btcupusdt',
    [Pair.BTCDOWNUSDT]: 'btcdownusdt',
    [Pair.GXSUSDT]: 'gxsusdt',
    [Pair.ARDRUSDT]: 'ardrusdt',
    [Pair.ERDBUSD]: 'erdbusd',
    [Pair.LENDUSDT]: 'lendusdt',
    [Pair.HBARBUSD]: 'hbarbusd',
    [Pair.MATICBUSD]: 'maticbusd',
    [Pair.WRXBUSD]: 'wrxbusd',
    [Pair.ZILBUSD]: 'zilbusd',
  },
};
export interface IPriceTicker {
  exchange: Exchange;
  pair: Pair;
  close: number;
  open: number;
  low: number;
  high: number;
  volume: number;
  timestamp: number;
  percent: number;
  percent_abs: number;
}

export interface ExchangeService {
  subscribe: (pair: Pair) => void;
  unsubscribe: (...args: any[]) => void;
  close: () => void;
}
